server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 2000